config/routes.rb
Rails.application.routes.draw do
  root "chapters#home"

  resources :chapters do
    collection do
      get "refresh"
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }
end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id             :bigint(8)        not null, primary key
#  base_asset_url :string
#  content        :text
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  vimeo_id       :string
#

class Chapter < ApplicationRecord
  before_save :append_toc_placeholder

  def append_toc_placeholder
    unless content.include?("{:toc}")
      content << "\n\n* Will be replaced with the ToC\n{:toc}"
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  REPO = ENV.fetch("CHAPTERS_REPO").freeze

  before_action :set_chapter, only: %i[show edit update destroy]

  def home
    @chapter = Chapter.find_by(id: 753)

    if @chapter.present?
      @page_title = "Home"

      render :show
    else
      redirect_to chapters_url
    end
  end

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.order(updated_at: :desc)
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @page_title = @chapter.title
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit; end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: "Chapter was successfully created." }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: "Chapter was successfully updated." }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def refresh
    if current_user.blank?
      redirect_to user_github_omniauth_authorize_path
    else
      require "open-uri"

      client = Octokit::Client.new(
        access_token: current_user.github_access_token,
      )

      client.contents(REPO).each do |file|
        if file.name.ends_with?(".md")
          chapter = Chapter.find_or_initialize_by(title: file.name)
          chapter.base_asset_url = "https://res.cloudinary.com/firstdraft/image/fetch/f_auto,q_auto:low/https://raw.githubusercontent.com/#{REPO}/master"
          chapter.content = open(file.download_url).read.gsub("![](", "![](#{chapter.base_asset_url}")
          chapter.save
        end
      end

      redirect_to root_url, notice: "Successfully imported from repo."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chapter
    @chapter = Chapter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chapter_params
    params.require(:chapter).permit(:title, :content, :vimeo_id, :user_id)
  end
end

app/views/chapters/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Chapter #<%= chapter.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Title</dt>
      <dd><%= chapter.title %></dd>

      <dt>Content</dt>
      <dd><%= chapter.content %></dd>

      <dt>Vimeo</dt>
      <dd><%= chapter.vimeo_id %></dd>

      <dt>User</dt>
      <dd><%= chapter.user %></dd>

    </dl>

    <div class="btn-group btn-group-justified mt-auto">
      <%= link_to_show_or_back chapter, fa_icon("search-plus"), fa_icon("chevron-left"), class: "btn btn-outline-secondary" %>

      <%= link_to fa_icon("edit"), edit_chapter_url(chapter), class: "btn btn-outline-secondary" %>

      <%= link_to fa_icon("trash-o"), chapter, method: :delete, data: { confirm: "Do you really want to delete this chapter?" }, class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(chapter.updated_at) %> ago
  </div>
</div>

app/views/chapters/_form.html.erb
<% was_validated = chapter.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(chapter, html: form_html_options) do |f| %>
  <div class="form-group">
    <% title_class = "form-control" %>
    <% title_was_invalid = chapter.errors.include?(:title) %>

    <% if was_validated %>
      <% if title_was_invalid %>
        <% title_class << " is-invalid" %>
      <% else %>
        <% title_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :title %>

    <%= f.text_field :title, class: title_class, placeholder: "Enter title" %>
    <% if title_was_invalid %>
      <% chapter.errors.full_messages_for(:title).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% content_class = "form-control" %>
    <% content_was_invalid = chapter.errors.include?(:content) %>

    <% if was_validated %>
      <% if content_was_invalid %>
        <% content_class << " is-invalid" %>
      <% else %>
        <% content_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :content %>

    <%= f.text_area :content, class: content_class, placeholder: "Enter content" %>
    <% if content_was_invalid %>
      <% chapter.errors.full_messages_for(:content).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% vimeo_id_class = "form-control" %>
    <% vimeo_id_was_invalid = chapter.errors.include?(:vimeo_id) %>

    <% if was_validated %>
      <% if vimeo_id_was_invalid %>
        <% vimeo_id_class << " is-invalid" %>
      <% else %>
        <% vimeo_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :vimeo_id %>

    <%= f.text_field :vimeo_id, class: vimeo_id_class, placeholder: "Enter Vimeo ID" %>
    <% if vimeo_id_was_invalid %>
      <% chapter.errors.full_messages_for(:vimeo_id).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/chapters/_list_item.html.erb
<%= link_to chapter, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= chapter.title %>
  </div>

  <span class="btn btn-sm btn-link text-secondary">
    <i class="far fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/chapters/_table_row.html.erb
<tr>
  <td>
    <%= chapter.title %>
  </td>

  <td>
    <%= chapter.content %>
  </td>

  <td>
    <%= chapter.vimeo_id %>
  </td>

  <td>
    <%= chapter.user %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to fa_icon("search-plus fw"), chapter, class: "btn btn-sm btn-outline-secondary" %>

      <%= link_to fa_icon("edit fw"), edit_chapter_url(chapter), class: "btn btn-sm btn-outline-secondary" %>

      <%= link_to fa_icon("trash-o fw"), chapter, method: :delete, data: { confirm: "Do you really want to delete this chapter?" }, class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </td>
</tr>

app/views/chapters/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Chapter #<%= @chapter.id %>
      </h2>

      <div class="card-body">
        <%= render "form", chapter: @chapter %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="far fa-plus fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/index.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Chapters
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @chapters, partial: "list_item", as: :chapter %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Chapter
      </h2>

      <div class="card-body">
        <%= render "form", chapter: @chapter %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="far fa-plus fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/show.html.erb
<% cache @chapter do %>
  <div class="chapter">
    <div class="chapter-rendered">
      <% if @chapter.vimeo_id.present? %>
        <div class="sticky-video">
          <div class="embed-container">
            <iframe src="https://player.vimeo.com/video/<%= @chapter.vimeo_id %>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
          </div>
        </div>

      <% end %>

      <% 
        doc = Kramdown::Document.new(
          @chapter.content,
          auto_ids: true,
          hard_wrap: false,
          input: "GFM",
        )
      %>

      <%= doc.to_draft_html.html_safe %>

      <% if false %>
      <p class="text-muted small font-italic">
        <% last_updated = @chapter.updated_at %>

        Last updated: <%= last_updated.in_time_zone("Central Time (US & Canada)").strftime("%A, %B #{@chapter.updated_at.day.ordinalize}, %Y at %l:%M%P") %>
      </p>

      <div class="col-md-6 offset-md-1 mt-2 mb-2" style="height: 5rem;">
        <a id="completion-notice" href="" class="btn btn-block btn-outline-success disabled" style="display: none;">
          <i class="far fa-check-circle"></i>

          Finished in

          <span id="main-timer">0</span>
        </a>
      </div>
      <% end %>

      <hr>
    </div>
  </div>

  <script>
    $(function() {
      setInterval(function() {
        reload_page();
      }, 60*60000);
    });

    function reload_page() {
      window.location.reload(true);
    }
  </script>
<% end %>